version: "3.3"
services:
  redis:
    image: redis:5
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - webnet
  postgres:
    image: postgis/postgis:11-3.3
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - data-volume:/data/db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - webnet
  mongo:
    image: mongo
    restart: always
    ports:
      - ${DATABASE_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data-volume:/data/db
    networks:
      - webnet
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@mongo:27017/
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume:
