apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-queue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/pixerpost/pixerpost_backend
          resources:
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockercfg
