apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
  annotations:
    kubernetes.io/service-account.name: <service-account-name>
spec:
  containers:
    - name: nginx-container
      image: nginx
  # serviceAccount: <service-account-name>
  # automountServiceAccountToken: <true/false>
