apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels:
    app: App1
    type: front-end
spec:
  selector:
    matchLabels:
      app: App1
  template:
    metadata:
      labels:
        app: App1
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 8080
