apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  securityContext:
    runAsUser: 1001
  containers:
    - name: nginx-container
      image: nginx
      securityContext:
        runAsUser: 1000
        capabilities:
          add:
            - "MAC_ADMIN"
