apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
      env:
        - name: APP_COLOR
          valueFrom:
            secretKeyRef:
              name: app-config
              key: APP_COLOR
        - name: APP_NAMEk
          value: "MY_APP_NAME"
  volumes:
    - name: app-secret-volume
      configMap:
        name: app-secret
