apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namesace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memtory: 10Gi
